### ISSUE TITLE
first tests

### ISSUE THREAD

**Issue by dsavina** [thecodingmachine/print.service#1]
After installing in Linux environment, I spotted a few flaws in the source :
- when input json is parsed, alue 0 on field 'order' leads to a Bad Request Exception. Also, 'headerUrl' and 'footerUrl' are not taken into account ; moreover, several hints in source code indicate that these are optional, nevertheless an execution error occurs when they are not set.
- the GET request attending to get the template file always leads to an empty file.
- temporary files cannot be found, even though they exist, due to processing of their path (absolute paths instead of project root relative paths end up in FileNotFound problems)
- not all temporary files are cleaned up after end of process, templates (.twig) are left undeleted. However they will not be reused afterwards, they will be downloaded again and stored in duplicate temporary files if requested again.

**Comment by gulien** [comment]
#2
